        .syntax unified
        .cpu cortex-m4
        .thumb

        .global setup_leds
        .global turn_on_rgb
        .global turn_off_rgb
        .global set_single_color
        .global get_color_value

@ FRDM-K66F RGB LED pins
@ Red   → PTC9  → GPIOC bit 9
@ Green → PTE6  → GPIOE bit 6
@ Blue  → PTA11 → GPIOA bit 11

        .equ GPIOA_PDOR, 0x400FF000
        .equ GPIOC_PDOR, 0x400FF080
        .equ GPIOE_PDOR, 0x400FF100

        .equ GPIOA_PDDR, 0x400FF014
        .equ GPIOC_PDDR, 0x400FF094
        .equ GPIOE_PDDR, 0x400FF114

        .text
        .align  2
        
@stack functionality, specifically the setup_leds function for the LEDS done with the help of AI.  Once we understood it, future code
@that used the stack was made ourselves by referencing lab 6.  The same applies to the other file as both are basically the exact same.
setup_leds:
        push    {lr}

        ldr     r0, =0x40048038        
        ldr     r1, [r0]
        orr     r1, r1, #(1<<9)        
        orr     r1, r1, #(1<<11)
        orr     r1, r1, #(1<<13)       
        str     r1, [r0]

        ldr     r0, =0x4004902C       
        movw    r1, #0x100
        str     r1, [r0]
        ldr     r0, =0x4004B024       
        str     r1, [r0]
        ldr     r0, =0x4004D018        
        str     r1, [r0]

        ldr     r0, =GPIOA_PDDR
        ldr     r1, [r0]
        orr     r1, r1, #(1<<11)
        str     r1, [r0]

        ldr     r0, =GPIOC_PDDR
        ldr     r1, [r0]
        orr     r1, r1, #(1<<9)
        str     r1, [r0]

        ldr     r0, =GPIOE_PDDR
        ldr     r1, [r0]
        orr     r1, r1, #(1<<6)
        str     r1, [r0]

        bl      turn_off_rgb
        pop     {pc}

turn_on_rgb:
        ldr     r0, =GPIOA_PDOR
        ldr     r1, [r0]
        bic     r1, r1, #(1<<11)       
        str     r1, [r0]

        ldr     r0, =GPIOC_PDOR
        ldr     r1, [r0]
        bic     r1, r1, #(1<<9)         
        str     r1, [r0]

        ldr     r0, =GPIOE_PDOR
        ldr     r1, [r0]
        bic     r1, r1, #(1<<6)        
        str     r1, [r0]
        bx      lr

turn_off_rgb:
        ldr     r0, =GPIOA_PDOR
        ldr     r1, [r0]
        orr     r1, r1, #(1<<11)       
        str     r1, [r0]

        ldr     r0, =GPIOC_PDOR
        ldr     r1, [r0]
        orr     r1, r1, #(1<<9)        
        str     r1, [r0]

        ldr     r0, =GPIOE_PDOR
        ldr     r1, [r0]
        orr     r1, r1, #(1<<6)        
        str     r1, [r0]
        bx      lr

@This section was also partially generated generated with AI.  The outline for it was written by us, but it was having errors so we asked AI to help generate it
@in a more effective way that didnt have errors or missing functionality.  The specific overhauls that were generated by will be mentioned in line
set_single_color:
        push    {r3, r4, lr}           
        mov     r3, r0                  
        bl      turn_off_rgb

        tst     r3, #1                
        beq     1f
        ldr     r4, =GPIOC_PDOR
        ldr     r1, [r4]
        bic     r1, r1, #(1<<9)      
        str     r1, [r4]
        @the branching to the 1, 2 and 3 optimizations were done with AI as well as the tst lines
1:      tst     r3, #2
        beq     2f
        ldr     r4, =GPIOE_PDOR
        ldr     r1, [r4]
        bic     r1, r1, #(1<<6)        
        str     r1, [r4]
2:      tst     r3, #4
        beq     3f
        ldr     r4, =GPIOA_PDOR
        ldr     r1, [r4]
        bic     r1, r1, #(1<<11)       
        str     r1, [r4]
3:
        pop     {r3, r4, pc}

get_color_value:
        cmp     r0, #7
@once we understood the blo, and branching to the 1, 2 ect we wrote these ourselves
        blo     1f
        movs    r0, #0
1:      ldr     r1, =color_table
        ldrb    r0, [r1, r0]
        bx      lr

        .align  2
color_table:
        .byte   0x01   
        .byte   0x03   
        .byte   0x02   
        .byte   0x06    
        .byte   0x04    
        .byte   0x05    
        .byte   0x07    

        .end
